services:
  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4567:4566"
    environment:
      - SERVICES=dynamodb,s3

  init:
    image: python:3.9-slim
    depends_on:
      - localstack
    command: sh -c "pip install boto3 && python -c 'import boto3,time; time.sleep(10); d=boto3.resource(\"dynamodb\",endpoint_url=\"http://localstack:4566\",region_name=\"us-east-1\",aws_access_key_id=\"test\",aws_secret_access_key=\"test\"); s=boto3.client(\"s3\",endpoint_url=\"http://localstack:4566\",region_name=\"us-east-1\",aws_access_key_id=\"test\",aws_secret_access_key=\"test\"); [d.create_table(TableName=\"items\",KeySchema=[{\"AttributeName\":\"id\",\"KeyType\":\"HASH\"}],AttributeDefinitions=[{\"AttributeName\":\"id\",\"AttributeType\":\"S\"}],BillingMode=\"PAY_PER_REQUEST\"),s.create_bucket(Bucket=\"items-bucket\")]' && sleep infinity"

  app:
    build: .
    ports:
      - "5002:5000"
    depends_on:
      - init

  test:
    build: .
    depends_on:
      - app
    command: sh -c "sleep 30 && python -m pytest -v"