name: Assignment 3 Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make scripts executable
      run: chmod +x test.sh

    - name: Run tests
      run: ./test.sh