name: Running pytest

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pipx
        run: python -m pip install --upgrade pipx

      - name: Install Poetry
        run: pipx install poetry

      - name: Add pytest
        run: poetry add pytest --dev

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run PyTest
        run: poetry run pytest
