name: Test Dockerfile

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./assignment2

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: |
        docker build -f Dockerfile.test -t test-image .
        docker run --rm test-image